#!/bin/bash

echo "🎤 Bible Verse App Demo"
echo "======================"
echo ""
echo "This Flutter app provides voice-activated Bible verse lookup with casting support."
echo ""
echo "✨ Key Features:"
echo "  • Voice recognition for Bible verse references"
echo "  • Cross-platform support (iOS, Android, Web)"
echo "  • Google Cast and Apple AirPlay integration"
echo "  • Dual-screen mode for casting"
echo "  • Smart verse format recognition"
echo ""
echo "🗣️  Supported voice commands:"
echo "  • 'John 3:16'"
echo "  • 'Romans 8:28'"
echo "  • 'First Corinthians 13:4'"
echo "  • 'Psalm 23 verse 1'"
echo "  • 'John chapter 3 verse 16'"
echo ""
echo "📱 Usage:"
echo "  1. Tap the microphone button (bottom right)"
echo "  2. Say any Bible verse reference"
echo "  3. The verse appears on screen"
echo "  4. Use cast button to display on external screens"
echo ""
echo "📁 Project Structure:"
echo "  lib/"
echo "  ├── main.dart           # App entry point"
echo "  ├── home_screen.dart    # Main UI with voice recognition"
echo "  ├── cast_screen.dart    # Casting display screen"
echo "  ├── bible_service.dart  # Bible verse lookup service"
echo "  └── cast_service.dart   # Google Cast/AirPlay integration"
echo ""
echo "🛠️  To run the app:"
echo "  flutter pub get"
echo "  flutter run"
echo ""
echo "For more information, see README.md"